const Erros = {
  AULA_DURACAO_ZERADA: "AULA_DURACAO_ZERADA",
  CAPITULO_SEM_AULAS: "CAPITULO_SEM_AULAS",
  CURSO_SEM_AULAS: "CURSO_SEM_AULAS",
  CURSO_SEM_DURACAO: "CURSO_SEM_DURACAO",
  DESCONHECIDO: "ERRO_DESCONHECIDO",
  DURACAO_NEGATIVA: "URACAO_NEGATIVA",
  DURACAO_ZERADA: "URACAO_ZERADA",
  EMAIL_INVALIDO: "EMAIL_INVALIDO",
  ID_INVALIDO: "ID_INVALIDO",
  NOME_CARACTERES_INVALIDOS: "NOME_CARACTERES_INVALIDOS",
  NOME_GRANDE: "NOME_GRANDE",
  NOME_PEQUENO: "NOME_PEQUENO",
  NOME_SEM_SOBRENOME: "NOME_SEM_SOBRENOME",
  NOME_VAZIO: "NOME_VAZIO",
  ORDEM_INVALIDA: "ORDEM_INVALIDA",
  SENHA_FRACA: "SENHA_FRACA",
  SENHA_HASH_INVALIDA: "SENHA_HASH_INVALIDA",
  URL_INVALIDA: "URL_INVALIDA)",
} as const;

export default Erros;
